### ISSUE TITLE
seurat 3.1.5 Jackstraw disabled on SCT assay

### ISSUE THREAD

**Issue by bio-la** [sansomlab/tenx#100]
new error :
https://github.com/satijalab/seurat/blame/master/R/dimensional_reduction.R

```
assay <- assay %||% DefaultAssay(object = object)
  if (IsSCT(assay = object[[assay]])) {
    stop("JackStraw cannot be run on SCTransform-normalized data.
         Please supply a non-SCT assay.")

```
branch fc-alternativebegin:
added a switch in seurat_begin.R to disable jackstraw in case assay== SCT

**Comment by gruensch** [comment]
May I know why JackStraw is disabled for SCT?

**Comment by anaccsilva** [comment]
I am having the same problems. Any ideas??

**Comment by snsansom** [comment]
It has been disabled by the Seurat authors in the most recent version of the package. As commented in the pipeline.yml we have found it not to give meaningful results when SCT normalisation is used. 

Commit 9148d5ec21490d4e7adb64e580a4594fd20dd49b fixes pipeline_seurat.py to no longer run the Jack Straw analysis when SCT normalisation is used.
