### ISSUE TITLE
PHATE map run on scaled data (not integrated)

### ISSUE THREAD

**Issue by kathrinjansen** [sansomlab/tenx#101]
In the case of integrated data, the PHATE algorithm is run on the scaled data slot from the Seurat object instead of an integrated reduced dimension. This could be made an option in the pipeline.yml or somewhere explicitly explained.

**Comment by snsansom** [comment]
Should be addressed by 9148d5ec21490d4e7adb64e580a4594fd20dd49b - please test.

**Comment by kathrinjansen** [comment]
This works now. Thanks for fixing.
