### ISSUE TITLE
fix factor y-axis for summary of number of degenes per cluster (deNumbers.*.png)

### ISSUE THREAD

**Issue by bio-la** [sansomlab/tenx#11]
can't git push my commit  (ERROR: This repository was archived so it is read-only.
fatal: The remote end hung up unexpectedly )

to fix factor/integer coercion (plot Summary of DE genes per cluster) (deNumbers.*.png)

in seurat_summariseMarkerNumbers.R 

nsummary <- data.frame(matrix(restmp,ncol=3,byrow=TRUE), **stringsAsFactors=F)**

**Comment by snsansom** [comment]
Hi Fabiola,

Can you please re-clone the repo and try again.

When the code was made public the repository was renamed to "tenx-legacy" and archived, and a new clean "tenx" repo created. I think your current repo is still pointing  (via a redirect) to tenx-legacy.

Best wishes,
Steve

**Comment by snsansom** [comment]
Now fixed with commit b226d85c30901b1ec571fe0fe6c16033de6a56b6
