### ISSUE TITLE
avg_logFC changed to avg_log2FC

### ISSUE THREAD

**Issue by Erinke89** [sansomlab/tenx#126]
Dear sansomlab,
I just wanted to notify you that a couple of scripts in the scxl pipeline are erroring because the output of Seurat;;FindMarkers now gives a DE genes table where the column header is avg_log2FC instead of avg_logFC. So anywhere this column header is mentioned e.g. in seurat_summariseMarkers.R and in tenxutils/R/Plot.R it causes errors.

Thank you!

**Comment by snsansom** [comment]
Many thanks Erinke - we plan to release an update for Seurat 4 compatibility soon. For now we are using Seurat v3 which can be installed from the CRAN archive.

**Comment by snsansom** [comment]
This has been fixed by the latest commit.
