### ISSUE TITLE
Error in filterGenesets: No genesets passed filters (summariseGenesets.R)

### ISSUE THREAD

**Issue by agammage** [sansomlab/tenx#37]
Hello,

While trying to run CCA-aligned data in pipeline_seurat.py, I incur the following error in summariseGenesets.R:

"Error in filterGenesets(genesets, min_foreground_genes = opt$mingenes,  : 
  No genesets passed filters"

Please find attached the tail of the following example files:
-  pipeline.log
- summarise.geneset.analysis.between.conditions.log 

It seems like all clusters except the final one (cluster 7) are processed successfully. However, perhaps owing to the small size of cluster 7, it produces too few markers to enrich any biological genesets.

Running the same CCA-aligned data on the previous version of pipeline_seurat.py (which did not contain the option for "min_fg_genes") does not produce an error.

Best wishes,
Anís

[issue1_tail_pipeline_log.pdf](https://github.com/sansomlab/tenx/files/3182692/issue1_tail_pipeline_log.pdf)
[issue1_tail_summariseGenesetsR_log.pdf](https://github.com/sansomlab/tenx/files/3182693/issue1_tail_summariseGenesetsR_log.pdf)

**Comment by snsansom** [comment]
Hi Anis,  please can you update your copy of gsfisher  (see: 7ca1843b369e1aaa402d2cca980045119524f134) and try running the pipeline again.

Thanks,
Steve
